#!/usr/bin/env bash
# A script that displays information about subdamins for a given domain

if [ $# -eq 1 ]; then
    doomain="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    doomain="$2.$1"
fi

dig $doomain | awk '/ANSWER SECTION:/{getline; split($1,b,"."); print "The subdomain", b[1], "is a", $4, "record and points to", $5}'
