#!/usr/bin/env bash
#Update package lists and Install nginx web server
sudo apt-get update && sudo apt-get install nginx

# Start the nginx service
sudo service nginx start

# Create html file with "Hello World!"
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart the nginx to apply changes
sudo service nginx restart
