#!/usr/bin/env bash
# update packages list and install nginx service
# configure  nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

sudo chmod -R 755 /var/www
# Overwrite html file with hello world
echo "Hello World!" > /var/www/html/index.html

sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=z9OGF0rYlss&ab_channel=Artisax permanent;" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

# Restart nginx service
sudo service nginx restart
