#!/usr/bin/env bash
# Bash script tha pings an IP address as an arg
# +accepts a string as an arg
# +display Usage:5-is_the_host_on_the_network{IP_ADDRESS} if no arg passed
# +ping the IP 5 times

if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
