#!/usr/bin/env bash
# Script that configures Nginx to listen on port 80 of all active IPv4 IPs

# Update packages and Ensure nginx is installed
apt-get update
apt-get install -y nginx

# Make Backup of the original config file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Modify the default config to listen on port 80 for all IPv4 IPs
sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;\n\tlisten [::]:80 default_server;/' /etc/nginx/sites-available/default

# Test the nginx configuration
nginx -t

# Restart the nginx
service nginx restart

# Ensure the nginx starts on boot
systemctl enable nginx
