#!/usr/bin/env bash
# Script that configures Nginx to listen on port 80 of all active IPv4 IPs

# Update packages and Ensure nginx is installed
apt-get update
apt-get install -y nginx

rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Test the nginx configuration
nginx -t

# Restart the nginx
service nginx restart

# Ensure the nginx starts on boot
systemctl enable nginx
