#!/usr/bin/env bash
# Configuring the nginx server to communicate with port 80, by using task0

# Creating a symbolic link
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Start nginx service
service nginx start
# Kill the mmain nginx process
kill "$(pgrep 'nginx' | head -1)"
