#!/usr/bin/env bash
# Configuring the nginx server to communicate with port 80, by using task0
make the fix short and sweet
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill apache2
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -g 'daemon off;' &
pkill nginx
