#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd,
#+ using the while loop + "IFS"

while IFS=":" read -r username urid home gpid shell info password
do
	echo "The user $username is part of the $gpid gang,"\
	"lives in $home and rides $shell."\
	"$urid's place is protected by the passcode $password,"\
	"more info about the user here: $info"
done < "/etc/passwd"
