#!/usr/bin/env bash
#  Bash script that displays "Best School" 10 times, but for the 9th iteration,
#+ displays "Best School" and then "Hi" on a new line

nm=1
while [ $nm -le 10 ]
do
	echo "Best School"
	if ((nm == 9))
	then
		echo "Hi"
	fi

	((nm++))
done
