#!/usr/bin/env bash
# Bash script that displays the time for 12 hrs and 59 mins:
# display hrs from 0 to 12
# display mins from 1 to 59

hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((hr++))
done
