#!/usr/bin/env bash
# Fixes a web server to run nginx as the nginx user listening on port 8080

# set a user in the config file by replace '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config file
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give the owner permissions to read and write to the config file
chmod u=rw,go=r /etc/nginx/nginx.conf
# start the nginx service with the new nginx user
sudo -u nginx service nginx start
